apiVersion: v1
kind: Service
metadata:
  name: receiver-service
  labels:
    name: receiver-service
    app: nuvalence
spec:
  type: LoadBalancer
  ports:
  - port: 8081
    targetPort: 8080
  selector:
    name: receiver-pod
    app: nuvalence
